const Sdata = [
  {
    imgscr: "images/img-1.jpg",
    title: "Madam Curie",
    desc: "Freelance photographer at Sp Pradhan Photography.",
    titleinfo: "painting",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-2.jpg",
    title: "Rasana Bajracharya",
    desc: "Matina",
    titleinfo: "sculpture",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-3.jpg",
    title: "Jack Ma",
    desc: "Chinese Dragon",
    titleinfo: "Handicraft",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-4.png",
    title: "Samundra man singh",
    desc: "Tripur Sundari Devi",
    titleinfo: "Drawing",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-1.jpg",
    title: "Madam Curie",
    desc: "Beautiful and colorful imagination",
    titleinfo: "painting",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-2.jpg",
    title: "Rasana Bajracharya",
    desc: "Matina",
    titleinfo: "sculpture",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-3.jpg",
    title: "Jack Ma",
    desc: "Chinese Dragon",
    titleinfo: "Handicraft",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-4.png",
    title: "Samundra man singh",
    desc: "Tripur Sundari Devi",
    titleinfo: "Drawing",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-1.jpg",
    title: "Madam Curie",
    desc: "Beautiful and colorful imagination",
    titleinfo: "painting",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-2.jpg",
    title: "Rasana Bajracharya",
    desc: "Matina",
    titleinfo: "sculpture",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-3.jpg",
    title: "Jack Ma",
    desc: "Chinese Dragon",
    titleinfo: "Handicraft",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-4.png",
    title: "Samundra man singh",
    desc: "Tripur Sundari Devi",
    titleinfo: "Drawing",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-1.jpg",
    title: "Madam Curie",
    desc: "Beautiful and colorful imagination",
    titleinfo: "painting",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-2.jpg",
    title: "Rasana Bajracharya",
    desc: "Matina",
    titleinfo: "sculpture",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-3.jpg",
    title: "Jack Ma",
    desc: "Chinese Dragon",
    titleinfo: "Handicraft",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-4.png",
    title: "Samundra man singh",
    desc: "Tripur Sundari Devi",
    titleinfo: "Drawing",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-1.jpg",
    title: "Madam Curie",
    desc: "Beautiful and colorful imagination",
    titleinfo: "painting",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-2.jpg",
    title: "Rasana Bajracharya",
    desc: "Matina",
    titleinfo: "sculpture",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-3.jpg",
    title: "Jack Ma",
    desc: "Chinese Dragon",
    titleinfo: "Handicraft",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-4.png",
    title: "Samundra man singh",
    desc: "Tripur Sundari Devi",
    titleinfo: "Drawing",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-1.jpg",
    title: "Madam Curie",
    desc: "Beautiful and colorful imagination",
    titleinfo: "painting",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-2.jpg",
    title: "Rasana Bajracharya",
    desc: "Matina",
    titleinfo: "sculpture",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-3.jpg",
    title: "Jack Ma",
    desc: "Chinese Dragon",
    titleinfo: "Handicraft",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-4.png",
    title: "Samundra man singh",
    desc: "Tripur Sundari Devi",
    titleinfo: "Drawing",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-1.jpg",
    title: "Madam Curie",
    desc: "Beautiful and colorful imagination",
    titleinfo: "painting",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-2.jpg",
    title: "Rasana Bajracharya",
    desc: "Matina",
    titleinfo: "sculpture",
  },
  {
    imgscr: "images/img-3.jpg",
    title: "Jack Ma",
    desc: "Chinese Dragon",
    titleinfo: "Handicraft",
  },
  {
    imgscr: "images/img-4.png",
    title: "Samundra man singh",
    desc: "Tripur Sundari Devi",
    titleinfo: "Drawing",
  },
  {
    imgscr: "images/img-1.jpg",
    title: "Madam Curie",
    desc: "Beautiful and colorful imagination",
    titleinfo: "painting",
  },
  {
    imgscr: "images/img-2.jpg",
    title: "Rasana Bajracharya",
    desc: "Matina",
    titleinfo: "sculpture",
  },
  {
    imgscr: "images/img-3.jpg",
    title: "Jack Ma",
    desc: "Chinese Dragon",
    titleinfo: "Handicraft",
    follower: "50 followers/16 work",
  },
  {
    imgscr: "images/img-4.png",
    title: "Samundra man singh",
    desc: "Tripur Sundari Devi",
    titleinfo: "Drawing",
    follower: "50 followers/16 work",
  },
];
export default Sdata;
